package co.streamx.fluent.SQL.MySQL;

import co.streamx.fluent.SQL.Keyword;

public enum TimeUnit implements Keyword {
    MICROSECOND, SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, YEAR, SECOND_MICROSECOND, MINUTE_MICROSECOND,
    MINUTE_SECOND, HOUR_MICROSECOND, HOUR_SECOND, HOUR_MINUTE, DAY_MICROSECOND, DAY_SECOND, DAY_MINUTE, DAY_HOUR,
    YEAR_MONTH,
}
