# Only build tags
if: tag IS present

language: java

jdk:
  - openjdk8

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Ptravis"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
